config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ghs_symbols
  resources :hazard_symbols
  resources :users
  resources :companies
  resources :substances
  resources :hphrases
  resources :pphrases
  resources :rphrases
  get 'substance/update_companies', as: 'update_companies'

  root "substances#index"
end

app/models/ghs_symbol.rb
class GhsSymbol < ApplicationRecord
  has_and_belongs_to_many :substances
end

app/controllers/ghs_symbols_controller.rb
class GhsSymbolsController < ApplicationController
  before_action :set_ghs_symbol, only: [:show, :edit, :update, :destroy]

  # GET /ghs_symbols
  # GET /ghs_symbols.json
  def index
    @ghs_symbols = GhsSymbol.all
  end

  # GET /ghs_symbols/1
  # GET /ghs_symbols/1.json
  def show
  end

  # GET /ghs_symbols/new
  def new
    @ghs_symbol = GhsSymbol.new
  end

  # GET /ghs_symbols/1/edit
  def edit
  end

  # POST /ghs_symbols
  # POST /ghs_symbols.json
  def create
    @ghs_symbol = GhsSymbol.new(ghs_symbol_params)

    respond_to do |format|
      if @ghs_symbol.save
        format.html { redirect_to @ghs_symbol, notice: 'Ghs symbol was successfully created.' }
        format.json { render :show, status: :created, location: @ghs_symbol }
      else
        format.html { render :new }
        format.json { render json: @ghs_symbol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ghs_symbols/1
  # PATCH/PUT /ghs_symbols/1.json
  def update
    respond_to do |format|
      if @ghs_symbol.update(ghs_symbol_params)
        format.html { redirect_to @ghs_symbol, notice: 'Ghs symbol was successfully updated.' }
        format.json { render :show, status: :ok, location: @ghs_symbol }
      else
        format.html { render :edit }
        format.json { render json: @ghs_symbol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ghs_symbols/1
  # DELETE /ghs_symbols/1.json
  def destroy
    @ghs_symbol.destroy
    respond_to do |format|
      format.html { redirect_to ghs_symbols_url, notice: 'Ghs symbol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ghs_symbol
      @ghs_symbol = GhsSymbol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ghs_symbol_params
      params.require(:ghs_symbol).permit(:title, :code, :description, :handling, :image)
    end
end

app/helpers/ghs_symbols_helper.rb
module GhsSymbolsHelper
end

app/views/ghs_symbols/_form.html.erb
<%= simple_form_for(@ghs_symbol) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :code %>
    <%= f.input :description %>
    <%= f.input :handling %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ghs_symbols/edit.html.erb
<h1>Editing Ghs Symbol</h1>

<%= render 'form', ghs_symbol: @ghs_symbol %>

<%= link_to 'Show', @ghs_symbol %> |
<%= link_to 'Back', ghs_symbols_path %>

app/views/ghs_symbols/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ghs Symbols</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Code</th>
      <th>Description</th>
      <th>Handling</th>
      <th>String</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ghs_symbols.each do |ghs_symbol| %>
      <tr>
        <td><%= ghs_symbol.title %></td>
        <td><%= ghs_symbol.code %></td>
        <td><%= ghs_symbol.description %></td>
        <td><%= ghs_symbol.handling %></td>
        <td><%= image_tag("ghs_img/" + ghs_symbol.image, size: "50x50") %></td>
        <td><%= link_to 'Show', ghs_symbol %></td>
        <td><%= link_to 'Edit', edit_ghs_symbol_path(ghs_symbol) %></td>
        <td><%= link_to 'Destroy', ghs_symbol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ghs Symbol', new_ghs_symbol_path %>

app/views/ghs_symbols/new.html.erb
<h1>New Ghs Symbol</h1>

<%= render 'form', ghs_symbol: @ghs_symbol %>

<%= link_to 'Back', ghs_symbols_path %>

app/views/ghs_symbols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ghs_symbol.title %>
</p>

<p>
  <strong>Code:</strong>
  <%= @ghs_symbol.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ghs_symbol.description %>
</p>

<p>
  <strong>Handling:</strong>
  <%= @ghs_symbol.handling %>
</p>

<p>
  <strong>Image:</strong>
  <%= @ghs_symbol.image %>
</p>

<%= link_to 'Edit', edit_ghs_symbol_path(@ghs_symbol) %> |
<%= link_to 'Back', ghs_symbols_path %>