config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ghs_symbols
  resources :hazard_symbols
  resources :users
  resources :companies
  resources :substances
  resources :hphrases
  resources :pphrases
  resources :rphrases
  get 'substance/update_companies', as: 'update_companies'

  root "substances#index"
end

app/models/hazard_symbol.rb
class HazardSymbol < ApplicationRecord
  has_and_belongs_to_many :substances
end

app/controllers/hazard_symbols_controller.rb
class HazardSymbolsController < ApplicationController
  before_action :set_hazard_symbol, only: [:show, :edit, :update, :destroy]

  # GET /hazard_symbols
  def index
    @hazard_symbols = HazardSymbol.all
  end

  # GET /hazard_symbols/1
  def show
  end

  # GET /hazard_symbols/new
  def new
    @hazard_symbol = HazardSymbol.new
  end

  # GET /hazard_symbols/1/edit
  def edit
  end

  # POST /hazard_symbols
  # POST /hazard_symbols.json
  def create
    @hazard_symbol = HazardSymbol.new(hazard_symbol_params)

    if @hazard_symbol.save
      fredirect_to @hazard_symbol, notice: 'Hazard symbol was successfully created.'
    else
      render :new
    end
  end

  def update
    if @hazard_symbol.update(hazard_symbol_params)
      redirect_to @hazard_symbol, notice: 'Hazard symbol was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @hazard_symbol.destroy
      redirect_to hazard_symbols_url, notice: 'Hazard symbol was successfully destroyed.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hazard_symbol
      @hazard_symbol = HazardSymbol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hazard_symbol_params
      params.require(:hazard_symbol).permit(:title, :code, :description, :image)
    end
end

app/helpers/hazard_symbols_helper.rb
module HazardSymbolsHelper
end

app/views/hazard_symbols/_form.html.erb
<%= simple_form_for(@hazard_symbol) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :code %>
    <%= f.input :description %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/hazard_symbols/edit.html.erb
<h1>Editing Hazard Symbol</h1>

<%= render 'form', hazard_symbol: @hazard_symbol %>

<%= link_to 'Show', @hazard_symbol %> |
<%= link_to 'Back', hazard_symbols_path %>

app/views/hazard_symbols/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hazard Symbols</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Code</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hazard_symbols.each do |hazard_symbol| %>
      <tr>
        <td><%= hazard_symbol.title %></td>
        <td><%= hazard_symbol.code %></td>
        <td><%= hazard_symbol.description %></td>
        <td><%= image_tag("hazard_img/" + hazard_symbol.image, size: "50x50") %></td>
        <td><%= link_to 'Show', hazard_symbol %></td>
        <td><%= link_to 'Edit', edit_hazard_symbol_path(hazard_symbol) %></td>
        <td><%= link_to 'Destroy', hazard_symbol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hazard Symbol', new_hazard_symbol_path %>

app/views/hazard_symbols/new.html.erb
<h1>New Hazard Symbol</h1>

<%= render 'form', hazard_symbol: @hazard_symbol %>

<%= link_to 'Back', hazard_symbols_path %>

app/views/hazard_symbols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @hazard_symbol.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= @hazard_symbol.image %>
</p>

<%= link_to 'Edit', edit_hazard_symbol_path(@hazard_symbol) %> |
<%= link_to 'Back', hazard_symbols_path %>