config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ghs_symbols
  resources :hazard_symbols
  resources :users
  resources :companies
  resources :substances
  resources :hphrases
  resources :pphrases
  resources :rphrases
  get 'substance/update_companies', as: 'update_companies'

  root "substances#index"
end

app/models/substance.rb
class Substance < ApplicationRecord
  belongs_to :user
  belongs_to :company
  has_and_belongs_to_many :hazard_symbols
  has_and_belongs_to_many :ghs_symbols
  has_and_belongs_to_many :hphrases
  has_and_belongs_to_many :pphrases
  has_and_belongs_to_many :rphrases

  has_attached_file :datasheet, styles: { thumb: ["60x60#", :jpg] }
  validates_attachment :datasheet, content_type: { content_type: "application/pdf" }
  validates :title, presence: true, uniqueness: true
  validates :date, presence: true
  validates :company_id, presence: true

end

app/controllers/substances_controller.rb
class SubstancesController < ApplicationController
  before_action :find_substance, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  after_action :verify_authorized, only: [:create, :update, :destroy]

  def index
    @substance = if params[:term]
      Substance.where('title LIKE ?', "%#{params[:term]}%").order('id DESC')
    else
      Substance.all.order("date DESC")
    end
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do

      pdf = Prawn::Document.new
      # The document grid on Prawn is just a table-like structure with a defined number of rows and columns.
      # There are some helpers to create boxes of content based on the grid coordinates.
      # define_grid accepts the following options:
      #  :rows          - Number of rows in the grid
      #  :columns       - Number of columns in the grid
      #  :gutter        - Padding of each cell
      #  :row_gutter    - Padding between rows
      #  :column_gutter - Padding between columns

      pdf.define_grid(:columns => 4, :rows => 12, :gutter => 5)
      pdf.font_size = 12
      # pdf.stroke_axis
      # pdf.grid.show_all

      pdf.grid([0, 0], [0, 2]).bounding_box do
        pdf.text @substance.title, :size => 24
        pdf.text @substance.company.name, :size => 20
      end

      pdf.grid([1, 0], [1, 2]).bounding_box do
        pdf.text @substance.application
      end


      number = @substance.hazard_symbols.count
      x_position = 500 - ((number - 1) * 45)
      @substance.hazard_symbols.each do |hazard_symbol|
        pdf.bounding_box([x_position, 660], width: 40) do
          pdf.svg IO.read("#{Rails.root}/app/assets/images/hazard_img/" + hazard_symbol.image), width: 40, hight: 40
          pdf.move_down 2
          pdf.text hazard_symbol.code, :align => :center
          x_position = x_position + 45
        end
      end

      number = @substance.ghs_symbols.count
      x_position = 490 - ((number - 1) * 55)
      @substance.ghs_symbols.each do |ghs_symbol|
        pdf.bounding_box([x_position, 600], width: 50) do
          pdf.svg IO.read("#{Rails.root}/app/assets/images/ghs_img/" + ghs_symbol.image), width: 50, hight: 50
          x_position = x_position + 55
        end
      end

      pdf.grid([2, 0], [2, 2]).bounding_box do
        pdf.text "R-Sätze:"
        pdf.move_down 2
        if @substance.rphrases.empty?
          pdf.text "-"
        else
          pdf.text @substance.rphrases.collect {|rphrase| rphrase.title}.join(', ')
        end
      end

      pdf.grid([3, 0], [3, 2]).bounding_box do
        pdf.text "H-Sätze:"
        pdf.move_down 2
        if @substance.hphrases.empty?
          pdf.text "-"
        else
          pdf.text @substance.hphrases.collect {|hphrase| hphrase.title}.join(', ')
        end

      end

      pdf.grid([4, 0], [4, 2]).bounding_box do
        pdf.text "P-Sätze:"
        pdf.move_down 2
          if @substance.pphrases.empty?
            pdf.text "-"
          else
            pdf.text @substance.pphrases.collect {|pphrase| pphrase.title}.join(', ')
          end
      end

      # Sends the PDF as inline document with name x.pdf
      send_data pdf.render, :filename => "x.pdf", :type => "application/pdf", :disposition => 'inline'
      end
    end
  end

  def new
    @substance = current_user.substances.build
  end

  def create
    authorize Substance
    @substance = current_user.substances.build(substance_params)

    if @substance.save
      redirect_to root_path, notice: "Successfully created new Substance"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    authorize @substance
    @substance = Substance.update(params[:id], substance_params)
    redirect_to root_path, notice: "Successfully updated Substance"
  end

  def destroy
    authorize @substance
    @substance.destroy
    redirect_to root_path, notice: "Successfully deleted Substance"
  end

private

  def find_substance
    @substance = Substance.find(params[:id])
  end

  def substance_params
    params.require(:substance).permit(:title, :company_id, :date, :application, :protectionlevel, :signalword, :unnumber, :hazardcode, :classificationcode, :packinggroup, :transportcategory, :qmax, :inhalation, :dermale, :datasheet, hphrase_ids:[], pphrase_ids:[], rphrase_ids:[], hazard_symbol_ids:[], ghs_symbol_ids:[])
  end
end

app/helpers/substance_helper.rb
module SubstanceHelper
end

app/views/substances/_form.html.haml
= simple_form_for @substance, validate: true, :html => { :multipart => true } do |f|
  - if @substance.errors.any?
    #errors
      %p
        = @substance.errors.count
        Prevented this substance from saving
      %ul
        - @substance.errors.full_messages.each do |msg|
          %li = msg
  .panel.panel-default
    .panel-body
      = f.input :title, wrapper_html: { title: 'Title' }, wrapper: :field4
      = f.input :company, required: false, wrapper_html: { title: 'Company' }, wrapper: :vertical_input_group4 do
        = f.association :company, label: false, include_blank: false, class: "form-control"
        %span.input-group-btn
          = link_to new_company_path, remote: true, class: "btn btn-default" do
            %span.glyphicon.glyphicon-plus
      = f.input :date, :as => :date_picker, wrapper_html: { title: 'Datum' }, wrapper: :field4
      = f.input :application, input_html: { class: 'form-control' }, wrapper_html: { title: 'application' }, wrapper: :field12
      = f.input :hazard_symbol_ids, :as => :check_boxes, wrapper: :field12, label: "Gefahrensymbol" do
        .row
        = f.collection_check_boxes :hazard_symbol_ids, HazardSymbol.all, :id, :code do |b|
          = b.label(class: "check_box", title: b.object.code + ": " + b.object.description) { b.check_box + b.object.code + image_tag("hazard_img/" + b.object.image, size: "50x50") }
      = f.input :pphrase_ids, :as => :check_boxes, wrapper: :field12, label: "R-Sätze" do
        .row
        = f.collection_check_boxes :rphrase_ids, Rphrase.order(:title), :id, :title do |b|
          = b.label(title: b.object.title + ": " + b.object.description) { b.check_box + b.text }
      = f.input :protectionlevel, collection: ["I", "II", "III", "IV"], :include_blank => "-", wrapper_html: { title: 'protectionlevel' }, wrapper: :field2
      = f.input :signalword, collection: ["Achtung", "Gefahr"], :include_blank => "-", wrapper_html: { title: 'signalword' }, wrapper: :field2
      .row
      = f.input :ghs_symbol_ids, :as => :check_boxes, wrapper: :field12, label: "GHS-Symbol" do
        .row
        = f.collection_check_boxes :ghs_symbol_ids, GhsSymbol.all, :id, :code do |b|
          = b.label(class: "check_box", title: b.object.code + ": " + b.object.description) { b.check_box + image_tag("ghs_img/" + b.object.image, size: "50x50") }
      = f.input :pphrase_ids, :as => :check_boxes, wrapper: :field12, label: "H-Sätze" do
        .row
        = f.collection_check_boxes :hphrase_ids, Hphrase.order(:title), :id, :title do |b|
          = b.label(title: b.object.title + ": " + b.object.description) { b.check_box + b.text }
      = f.input :pphrase_ids, :as => :check_boxes, wrapper: :field12, label: "P-Sätze" do
        .row
        = f.collection_check_boxes :pphrase_ids, Pphrase.order(:title), :id, :title do |b|
          = b.label(title: b.object.title + ": " + b.object.description) { b.check_box + b.text }
      .row
      .form-group.col-md-4
        %strong Gefährdungen
        = f.input :inhalation
        = f.input :dermale
        %strong Angaben zum Transport
      .row
      = f.input :unnumber, wrapper_html: { title: 'UN-Number' }, wrapper: :field2
      = f.input :classificationcode, wrapper_html: { title: 'classificationcode' }, wrapper: :field2
      = f.input :packinggroup, collection: ["I", "II", "III"], :include_blank => "-", wrapper: :field2
      = f.input :transportcategory, collection: 1..3, :include_blank => "-", wrapper: :field2
      = f.input :qmax, :as => :string, wrapper: :field2
      .row
      .col-md-4
        %strong Sicherheitsdatenblatt
        %br
        -if @substance.datasheet?
          = link_to image_tag(@substance.datasheet.url(:thumb), :title => "Sicherheitsdatenblatt"), @substance.datasheet.url, class: 'img-thumbnail'
      .row
      .form-group.col-md-4
        = f.input :datasheet, as: :file, wrapper: :vertical_file_input
      .row
      .col-md-4
        = f.button :submit, class: "btn btn-primary"

app/views/substances/_substance_row.html.haml
%tr
  %td= link_to substance.title, substance
  %td= substance.company.name
  %td= l substance.date
  %td= substance.application
  %td= substance.hazard_symbols.collect { |hazard_symbol| image_tag("hazard_img/" + hazard_symbol.image, size: "25x25", :title => hazard_symbol.code + ": " + hazard_symbol.description)}.join("\n").html_safe
  %td= substance.rphrases.collect {|rphrase| rphrase.title}.join ', '
  %td= substance.protectionlevel
  %td= substance.ghs_symbols.collect { |ghs_symbol| image_tag("ghs_img/" + ghs_symbol.image, size: "30x30", :title => ghs_symbol.code + ": " + ghs_symbol.description)}.join("\n").html_safe
  %td= substance.signalword
  %td= substance.hphrases.collect {|hphrase| hphrase.title}.join ', '
  %td= substance.pphrases.collect {|pphrase| pphrase.title}.join ', '
  %td
    - if substance.datasheet?
      = link_to image_tag(substance.datasheet.url(:thumb)), substance.datasheet.url
  %td
    - if user_signed_in?
      = link_to edit_substance_path(substance), class: "btn btn-default btn-xs" do
        %span.glyphicon.glyphicon-pencil
      = link_to substance_path(substance), method: :delete, data: { confirm: t('are_you_sure?') }, class: "btn btn-default btn-xs" do
        %span.glyphicon.glyphicon-remove

app/views/substances/edit.html.haml
.container
  %legend Edit Substance

  = render 'form'

  %br/

  = link_to "Back", root_path, class: "btn btn-default"

app/views/substances/index.html.haml
.container-fluid
  = form_tag(substances_path, method: :get) do
    .row
      .col-md-3
        .input-group
          = text_field_tag :term, params[:term], placeholder: t('Search')+('...'), class: "form-control"
          .input-group-btn
            = button_tag 'Search', name: nil, class: "btn btn-default btn" do
              %span.glyphicon.glyphicon-search
    %br

    .row
      .col-md-12
        .panel.panel-default
          .panel-body
            %table.table.table-striped.data-table#substance-table
              %thead
                %tr
                  %th.col-md-1= t('title')
                  %th.col-md-1= t('company')
                  %th Datum
                  %th.col-md-2= t('application')
                  %th.col-md-1= t('hazard symbol')
                  %th.col-md-1= t('R-Phrase')
                  %th= t('protectionlevel')
                  %th.col-md-1= t('GHS-Symbol')
                  %th= t('signalword')
                  %th.col-md-1= t('H-Phrase')
                  %th.col-md-1= t('P-Phrase')
                  %th
                  %th
              %tbody
                - @substance.each do |substance|
                  = render 'substance_row', substance: substance

app/views/substances/new.html.haml
.container
  %legend New Substance

  = render 'form'

  %br/

  = link_to "Back", root_path, class: "btn btn-default"

app/views/substances/show.html.haml
.container
  .row
    .col-md-12
      .panel.panel-default
        .panel-body
          .row
            .col-md-6
              %h1= @substance.title
            .col-md-6
              .text-right
                = link_to "PDF", substance_path(@substance, :format => 'pdf'), class: "btn btn-default btn-xs"
          .row
            .col-md-6
              %h2= @substance.company.name
            .col-md-6
              - @substance.hazard_symbols.each do |hazard_symbol|
                %figure
                  = image_tag("hazard_img/" + hazard_symbol.image, size: "50x50", :title => hazard_symbol.code + ": " + hazard_symbol.description)
                  %figcaption
                    = hazard_symbol.code
          .row
            .col-md-6
              %h3= @substance.application
            .col-md-6
              = @substance.ghs_symbols.collect { |ghs_symbol| image_tag("ghs_img/" + ghs_symbol.image, size: "50x50", :title => ghs_symbol.code + ": " + ghs_symbol.description)}.join("\n").html_safe
          .row
            .col-md-6
              - if @substance.rphrases.empty?
                R-Sätze: -
              - else
                R-Sätze: #{@substance.rphrases.collect {|rphrase| rphrase.title}.join ', '}
            .col-md-6
          .row
            .col-md-6
              - if @substance.protectionlevel?
                Sicherheitsstufe: #{@substance.protectionlevel}
              -  else
                Sicherheitsstufe: -
            .col-md-6
          .row
            .col-md-6
              - if @substance.signalword?
                Signalwort: #{@substance.signalword}
              - else
                Singnalwort: -
            .col-md-6
          .row
            .col-md-6
              - if @substance.inhalation?
                Inhalativ wirkend
              - if @substance.dermale?
                Dermal wirkend
            .col-md-6
          .row
            .col-md-6
              - if @substance.hphrases.empty?
                H-Sätze: -
          .row
            .col-md-6
              - if @substance.pphrases.empty?
                P-Sätze: -
              - else
                P-Sätze: #{@substance.pphrases.collect {|pphrase| pphrase.title}.join ', '}
            .col-md-6
          .row
            .col-md-6
              - if @substance.datasheet?
                Sicherheitsdatenblatt vom #{l @substance.date}:
                %br
                = link_to image_tag(@substance.datasheet.url(:thumb)), @substance.datasheet.url
  = link_to "Home", root_path, class: "btn btn-default btn-xs"