config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :ghs_symbols
  resources :hazard_symbols
  resources :users
  resources :companies
  resources :substances
  resources :hphrases
  resources :pphrases
  resources :rphrases
  get 'substance/update_companies', as: 'update_companies'

  root "substances#index"
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :substances
  validates :name, presence: true, uniqueness: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:edit, :update, :destroy]

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def show
  end

  def edit
  end

  def create
    @company = Company.create(company_params)
  end

  def update
    if @company.update(company_params)
      redirect_to companies_url, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @company.destroy
    redirect_to companies_url, notice: 'Company was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.haml
#company-modal.modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        %h4.modal-title= title
      = simple_form_for @company, validate: true, remote: true do |f|
        = f.error_notification
        .modal-body
          = f.input :name
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
          = f.button :submit, class: "btn btn-primary"

app/views/companies/_row.html.haml
%tr{:id => company.id}
  %td= company.name
  %td= link_to 'Edit', edit_company_path(company), remote: true, class: "btn btn-default btn-xs"
  %td= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }

app/views/companies/create.js.erb
<% if @company.errors.blank? %>
  /*
  First append new company select options
  */
  $('#substance_company_id').append($('<option>', {
    value: <%= @company.id %>,
    text: '<%= @company.name %>'
  }));
  /*
  Reorder Company selectbox
  */
  $('#substance_company_id').html( $('#substance_company_id'+" option").sort(function(a, b) {
       return a.text == b.text ? 0 : a.text < b.text ? -1 : 1
    }));
  $('#substance_company_id').val(<%= @company.id %>);

  alert('Company created');
  $('#company-modal').modal('hide');
<% else %>
   alert('<%= @company.errors.full_messages[0] %>');
<% end %>

app/views/companies/edit.js.erb
$('<%= j render "form", title: "Edit Company" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/companies/index.html.haml
%p#notice= notice
%h1 Companies
%table
  %thead
    %tr
      %th Company
  %tbody
    - @companies.each do |company|
      %tr
        %td= company.name
        %td= link_to 'Edit', edit_company_path(company), remote: true, class: "btn btn-default btn-xs"
        %td= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Company', new_company_path, remote: true, class: "btn btn-default btn-xs"

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/new.js.erb
$('<%= j render "form", title: "New Company" %>').on('hidden.bs.modal', function (e) {
  console.log("Modal hidden");
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();